name = "pinger-analytics"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "396c740c5669a95511ef46c213bb0466"


[vars]
ANALYTICS_ALLOWED = true

routes = [{ pattern = "pinger-analytics.worker.imadam.io/*" }]

zone_id = "a34a04bbaa9e618c8e8e3249fa9d4fff"
