name: Deploy Analytics Worker

on:
  push:
    paths:
      - "analytics-worker/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "analytics-worker"
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
